### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by BrycensRanch** [shirshak55/edge-paths#13]
# Semver Versioning

I know this may be a big ask, but... The release notes are bad. With Conventional Commits, users know what they're updating to and why the version was bumped up without having to view all your commits. 

Btw, great project! 

For an example, [view my project](https://github.com/BrycensRanch/Chatting-Platform). It automatically releases and generates informative changelogs via GitHub Actions

**Comment by shirshak55** [comment]
@BrycensRanch 

We can make a proper release note. We didn't do that till now because edge-paths is a small project. We publish what changes we made via PR itself. We won't have any major changes unless Microsoft Edge does something drastic. 

Also, if you wanna send a pull request to make a proper release note etc.., I will happily accept the pull request.

Addendum:

We will publish proper release notes on major changes from the next releases.


If you wanna pull request feel free to open new issue. Thank You.
